### ISSUE TITLE
Notes and fixes on callbacks for functions with async/await

### ISSUE THREAD

**Issue by ioanniswd** [Cyb3rN4u7/Simple-AWS-Service#4]
PR: #3

**Comment by ioanniswd** [comment]
Promises do not need to be awaited in `utils/backupOps.js`

**Comment by achimoraites** [comment]
i have removed the await in `utils/backupOps.js`

**Comment by ioanniswd** [comment]
functions do not need to be async in `utils/backupOps.js`

**Comment by achimoraites** [comment]
updateTable as well ?

**Comment by ioanniswd** [comment]
async is only required if something will be awaited in the function

**Comment by achimoraites** [comment]
thanks 👍

**Comment by achimoraites** [comment]
committed the changes

**Comment by ioanniswd** [comment]
This was fun

**Comment by achimoraites** [comment]
thanks ! 
learned some cool stuff !
